// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe3UA_V8UPZXD1JempcR5oE_B_wCYs8m0',
    appId: '1:821959296880:web:23284a08256fc104b8b1b5',
    messagingSenderId: '821959296880',
    projectId: 'portfolio-web-7ea37',
    authDomain: 'portfolio-web-7ea37.firebaseapp.com',
    storageBucket: 'portfolio-web-7ea37.firebasestorage.app',
    measurementId: 'G-92KQLSJ12L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1XUsqpCN0nQOXAPXAwf6UW0G-fHLdeFg',
    appId: '1:821959296880:android:01a2f517823a1d5fb8b1b5',
    messagingSenderId: '821959296880',
    projectId: 'portfolio-web-7ea37',
    storageBucket: 'portfolio-web-7ea37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUhr5rxRbRjFp-4PkgHFJPwyvFe8lBMTk',
    appId: '1:821959296880:ios:fe9e9a38eb5d44b5b8b1b5',
    messagingSenderId: '821959296880',
    projectId: 'portfolio-web-7ea37',
    storageBucket: 'portfolio-web-7ea37.firebasestorage.app',
    iosBundleId: 'com.example.portfolioWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUhr5rxRbRjFp-4PkgHFJPwyvFe8lBMTk',
    appId: '1:821959296880:ios:fe9e9a38eb5d44b5b8b1b5',
    messagingSenderId: '821959296880',
    projectId: 'portfolio-web-7ea37',
    storageBucket: 'portfolio-web-7ea37.firebasestorage.app',
    iosBundleId: 'com.example.portfolioWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe3UA_V8UPZXD1JempcR5oE_B_wCYs8m0',
    appId: '1:821959296880:web:fa93ba38725c73f6b8b1b5',
    messagingSenderId: '821959296880',
    projectId: 'portfolio-web-7ea37',
    authDomain: 'portfolio-web-7ea37.firebaseapp.com',
    storageBucket: 'portfolio-web-7ea37.firebasestorage.app',
    measurementId: 'G-H1G1PTE5EF',
  );
}
